apiVersion: v1
kind: Service
metadata:
  name: TomaTask-springboot-service
  annotations:
    oci.oraclecloud.com/loadbalancer-policy: "IP_HASH"
spec:
  type: NodePort
  externalTrafficPolicy: Local

  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: TomaTask-springboot
---
#this is new stuff for hosting on the load balancer
apiVersion: v1
kind: Service
metadata:
  name: TomaTask-backend-router
spec:
  selector:
    app: TomaTask-springboot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: TomaTask-springboot-deployment
spec:
  selector:
    matchLabels:
      app: TomaTask-springboot
  replicas: 2
  template:
    metadata:
      labels:
        app: TomaTask-springboot
        version: v1
    spec:
      containers:
        - name: TomaTask-springboot
          image: agileimage:0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: db_user
              value: "TOMATITOS"
            - name: db_url
              value: "jdbc:oracle:thin:@reacttodoi4tcl_tp?TNS_ADMIN=/mtdrworkshop/creds"
            - name: todo.table.name
              value: "todoitem"
            - name: driver_class_name
              value: "oracle.jdbc.OracleDriver"
            - name: OCI_REGION
              value: "OCI_REGION"
            - name: dbpassword
              valueFrom:
                secretKeyRef:
                  name: dbuser
                  key: dbpassword
                  optional: true
            - name: ui_username
              value: "admin"
            - name: ui_password
              value: "none0001"
          volumeMounts:
            - name: creds
              mountPath: /mtdrworkshop/creds
          ports:
            - containerPort: 8080
      restartPolicy: Always
      volumes:
        - name: creds
          secret:
            secretName: db-wallet-secret
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: TomaTask-springboot
---

