name: GraalVM build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Java version
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: "Extract files"
        run:  cd MtdrSpring && \
              wget https://objectstorage.mx-queretaro-1.oraclecloud.com/n/axohot8ponib/b/reacttodo-uazrb/o/deployment_config.tgz && \
              tar -xzvf deployment_config.tgz && \
              source env.sh && \

      - name: "Docker Login"
        run: cat at.cfg | docker login -u "axohot8ponib/a01198666@tec.mx" --password-stdin mx-
        
      - name: "Build"
        run: cd MtdrSpring;
             source env.sh;
             (cd backend;source build.sh)
